name: RSOLV Security Scanner

on:
  # Automatic scanning on every push
  push:
    branches: [ main, master, develop ]
  
  # Manual trigger for on-demand scans
  workflow_dispatch:
  
  # Weekly scheduled scan (every Monday at 2 AM)
  schedule:
    - cron: '0 2 * * 1'
  
  # Trigger on issue events for automated fixes
  issues:
    types: [labeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    if: github.event_name \!= 'issues'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run RSOLV Security Scan
        uses: RSOLV-dev/rsolv-action@v1
        with:
          # Your RSOLV API key (stored as a secret)
          api_key: ${{ secrets.RSOLV_API_KEY }}
          
          # Set scan_mode to 'scan' for vulnerability detection
          scan_mode: 'scan'
          
          # Label to add to created issues
          issue_label: 'security'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Automatic fix generation when issues are labeled
  fix-vulnerabilities:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issues' && 
      github.event.action == 'labeled' &&
      contains(github.event.label.name, 'rsolv:automate')
    steps:
      - name: Generate Security Fix
        uses: RSOLV-dev/rsolv-action@v1
        with:
          api_key: ${{ secrets.RSOLV_API_KEY }}
          scan_mode: 'fix'
          issue_number: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
EOF < /dev/null